### ISSUE TITLE
Error loading exercise

### ISSUE THREAD

**Issue by guna32** [stevekane/promise-it-wont-hurt#160]
when i select exercises i see this error

/usr/local/lib/node_modules/promise-it-wont-hurt/node_modules/@timothygu/workshopper-wrappedexec/wrappedexec.js:16
  var dataPath = path.join(os.tmpDir(), '~workshopper.wraptmp.' + process.pid)
                              ^

TypeError: os.tmpDir is not a function
    at fix (/usr/local/lib/node_modules/promise-it-wont-hurt/node_modules/@timothygu/workshopper-wrappedexec/wrappedexec.js:16:31)
    at wrappedexec (/usr/local/lib/node_modules/promise-it-wont-hurt/node_modules/@timothygu/workshopper-wrappedexec/wrappedexec.js:93:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/promise-it-wont-hurt/exercises/fulfill_a_promise/exercise.js:27:12)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Workshopper.loadExercise (/usr/local/lib/node_modules/promise-it-wont-hurt/node_modules/@timothygu/workshopper/workshopper.js:484:14)

**Comment by dbelozerovx1** [comment]
https://github.com/stevekane/promise-it-wont-hurt/issues/159

Check this solution, it helps
