### ISSUE TITLE
throw_an_error completion dependent on node version?

### ISSUE THREAD

**Issue by synthe** [stevekane/promise-it-wont-hurt#30]
Running the throw_an_error exercise checks the stack trace as part of the completion condition. When using Node 0.11.13 I get the following response. 

```
"  stack: 'SyntaxError: Unexpected token o\\n    at Object.parse (native)\\n    at parsePromised (/Users/user/dev/nodeschool/promise/ex06.js:10:14)\\n    at Object.<anonymous> (/Users/user/dev/nodeschool/promise/ex06.js:20:1)\\n    at Module._compile (module.js:449:26)\\n    at Object.Module._extensions..js (module.js:467:10)\\n    at Module.load (module.js:349:32)\\n    at Function.Module._load (module.js:305:12)\\n    at Function.Module.runMain (module.js:490:10)\\n    at startup (node.js:124:16)\\n    at node.js:807:3' }"
!=
"  stack: 'SyntaxError: Unexpected token o\\n    at Object.parse (native)\\n    at parsePromised (/Users/user/.nvm/v0.11.13/lib/node_modules/promise-it-wont-hurt/problems/throw_an_error/solution.js:8:19)\\n    at Object.<anonymous> (/Users/user/.nvm/v0.11.13/lib/node_modules/promise-it-wont-hurt/problems/throw_an_error/solution.js:17:1)\\n    at Module._compile (module.js:449:26)\\n    at Object.Module._extensions..js (module.js:467:10)\\n    at Module.load (module.js:349:32)\\n    at Function.Module._load (module.js:305:12)\\n    at Function.Module.runMain (module.js:490:10)\\n    at startup (node.js:124:16)\\n    at node.js:807:3' }"
```

The condition should probably have you pass err.message to the rejection to make it complete-able. Otherwise it expects the stack trace including line numbers and filenames to be exactly the same.

The first line of the pass/fail check works correctlly

**Comment by TimothyGu** [comment]
This is not reproducible (anymore?) with io.js so I'm closing this for now.
