### ISSUE TITLE
'More functional' solution is not working

### ISSUE THREAD

**Issue by PaoloLaurenti** [stevekane/promise-it-wont-hurt#56]
I tried to implement the 'More functional" challenge but I wasn't able to solve it.
Next I got the solution in order to better understand the concepts behind this challenge, but whenever I run the code I obtain the following error:

[...]/node_modules/lodash/index.js:3865
      return metaMap.get(func);
                     ^
TypeError: Invalid value used as weak map key
    at WeakMap.get (native)
    at getData (/Users/paolo/sw/learning/js/node/nodeschool/node_modules/lodash/index.js:3865:22)
    at isLaziable (/Users/paolo/sw/learning/js/node/nodeschool/node_modules/lodash/index.js:4151:18)
    at Function.<anonymous> (/Users/paolo/sw/learning/js/node/nodeschool/node_modules/lodash/index.js:3310:23)
    at Object.<anonymous> (/Users/paolo/sw/learning/js/node/nodeschool/promise-it-wont-hurt/more-functional.js:29:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

I think the problem is about lodash bind used with string.prototype concat but I don't quite understand where is the problem.

Thank in advance
  Paolo

**Comment by PaoloLaurenti** [comment]
In addition I made a test and the following code works perfectly:

var qhttp = require('q-io/http')
, _ = require('lodash')
, cachePath = "http://localhost:7000/"
, dbPath = "http://localhost:7001/";

var concat = function(suffix) {
  return this + suffix;
};

//var buildDbPath = _.bind(String.prototype.concat, dbPath);
var buildDbPath = _.bind(concat, dbPath);

qhttp.read(cachePath)
.then(_.flow(buildDbPath, qhttp.read))
.then(_.flow(JSON.parse, console.log))
.then(null, console.error)
.done();

*I replaced compose with flow, to me left to right declaration is clearer than right to left.

**Comment by TimothyGu** [comment]
This lesson was removed in the latest version of promise-it-wont-hurt.
