### ISSUE TITLE
Exercies 10 - Can't be solved

### ISSUE THREAD

**Issue by probil** [stevekane/promise-it-wont-hurt#99]
I have a correct solution for exercise 10 but the app can't accept it because it compares path to may solution with path to correct solution. Check line number 7 there

```
Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   "1"                                 ==    "1"                                
   "2"                                 ==    "2"                                
   "3"                                 ==    "3"                                
   "4"                                 ==    "4"                                
   "5"                                 ==    "5"                                
   "Error: OH NOES"                    ==    "Error: OH NOES"                   
   "    at alwaysThrows (/media/multimedia/Code/node-js/workshop_promises/important_rule.js:4:9)" !=    "    at alwaysThrows (/usr/lib/node_modules/promise-it-wont-hurt/exercises/an_important_rule/solution/solution.js:7:9)"
   "    at process._tickCallback (internal/process/next_tick.js:103:7)" ==    "    at process._tickCallback (internal/process/next_tick.js:103:7)"
   "    at Module.runMain (module.js:592:11)" ==    "    at Module.runMain (module.js:592:11)"
   "    at run (bootstrap_node.js:394:7)" ==    "    at run (bootstrap_node.js:394:7)"
   "    at startup (bootstrap_node.js:149:9)" ==    "    at startup (bootstrap_node.js:149:9)"
   "    at bootstrap_node.js:509:3"    ==    "    at bootstrap_node.js:509:3"   
   ""                                  ==    ""                                 

────────────────────────────────────────────────────────────────────────────────

✗ Submission results did not match expected!

# FAIL

Your solution to An important rule didn't pass. Try again!

```

7-th respose line will never be equal. So, some changes need to make it work correctly

**Comment by gabrielkunkel** [comment]
Yes I have the same issue. I used the stored solution for this.

**Comment by gabrielkunkel** [comment]
I even tried this solution: 

```
function alwaysThrows() {
  throw new Error("Error: OH NOES");
}

function iterate(arg) {
  console.log(arg);
  return arg + 1;
}

function printErrorMessage(err) {
  console.log(err.message);
}

Promise.resolve(iterate(1))
  .then(iterate)
  .then(iterate)
  .then(iterate)
  .then(iterate)
  .then(alwaysThrows)
  .then(iterate)
  .then(iterate)
  .then(iterate)
  .then(iterate)
  .then(iterate)
  .then(null, printErrorMessage);

```

And although it looks great in the console:

```
Gabriels-MacBook-Pro:promise-shop gabrielkunkel$ node program.js
1
2
3
4
5
Error: OH NOES
```

It still doesn't pass the tests:

```
                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   "1"                                 ==    "1"                                
   "2"                                 ==    "2"                                
   "3"                                 ==    "3"                                
   "4"                                 ==    "4"                                
   "5"                                 ==    "5"                                
   "Error: OH NOES"                    ==    "Error: OH NOES"                   
   ""                                  !=    "    at alwaysThrows (/usr/local/lib/node_modules/promise-it-wont-hurt/exercises/an_important_rule/solution/solution.js:7:9)"
                                       !=    "    at Function.Module.runMain (module.js:577:11)"
                                       !=    "    at startup (node.js:160:18)"  
                                       !=    "    at node.js:449:3"             
                                       !=    ""                                 

────────────────────────────────────────────────────────────────────────────────
```

**Comment by gabrielkunkel** [comment]
I see... It looks like the problem is with workshopper?

**Comment by probil** [comment]
@gabrielkunkel  Yeah. Just skip this exercise for now

**Comment by gabrielkunkel** [comment]
@probil Well, yeah. I was trying to see how I might fix it, but I'm not sure I have the time. It seems like workshopper[-adventure] is wokring against us.
